export const AUTH_LOGIN_REQUEST = "auth/LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "auth/LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "auth/LOGIN_FAILURE";
export const AUTH_REGISTER_REQUEST = "auth/REGISTER_REQUEST";
export const AUTH_REGISTER_SUCCESS = "auth/REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "auth/REGISTER_FAILURE";
export const AUTH_TOKEN_VALIDATE_REQUEST = "auth/TOKEN_VALIDATE_REQUEST";
export const AUTH_TOKEN_VALIDATE_SUCCESS = "auth/TOKEN_VALIDATE_SUCCESS";
export const AUTH_TOKEN_VALIDATE_FAILURE = "auth/TOKEN_VALIDATE_FAILURE";
export const CREATE_PRODUCT_REQUEST="CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS="CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE="CREATE_PRODUCT_FAILURE";
export const AUTH_LOGOUT = "auth/LOGOUT";


